### ISSUE TITLE
Suggested change of A*

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#1]
The lecturerer suggested that we might improve the performance of our A\* implementation if we change the neighbours function to also return the cost of each neighbour (instead of having different functions for neighbours and cost). This way, we might avoid complex recalculations for some problems (the Shrdlite problem is probably an example since he suggested it :P )

**Comment by HalfLeif** [comment]
I guess it could help in the project but for the three examples we have the computational cost would be exactly the same.

**Comment by HalfLeif** [comment]
Implemented this anyway in the refactoring of A_, IDA_
