### ISSUE TITLE
Crash situation

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#13]
In the complex world, the command "put the white ball above a table above a brick" causes the program to crash (no errors, no warnings, just crash).

**Comment by HalfLeif** [comment]
Now it gives planner iterations error, even for this simple case:
put the white ball above a box above a brick

**Comment by HalfLeif** [comment]
However, "put the white ball on a box that is on a brick" works perfectly

**Comment by HalfLeif** [comment]
This is probably what is interpreted:
"put the ball that is on a box on a brick"

Which should fail in Interpreter, not in Planner

**Comment by HalfLeif** [comment]
Hmm: "put the white ball on a box on a brick" gives the correct interpretation but cant be found...

**Comment by HalfLeif** [comment]
Fixed in development

**Comment by HalfLeif** [comment]
The original sentence
"put the white ball above a table above a brick"
gives no interpretation in the start state because the ball is not above a table AND the table is not above a brick. So in either way, there is no valid interpretation.

**Comment by HalfLeif** [comment]
Ie, the grammar works like this (on a conceptual level): it inserts "that is". So "put the white ball above a table above a brick" becomes either
1) "put the white ball that is above a table above a brick"
2) "put the white ball above a table that is above a brick"

which is entirely different from a potential "stack" command
