### ISSUE TITLE
Ambiguity filter out non-supportive objects?

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#15]
small world: "put the large ball in the box"

should not list small box as a location.

**Comment by jeffpolk230** [comment]
checkout jeff_fix_amb for this enhancement :)

**Comment by HalfLeif** [comment]
Looking jeff_fix_amb right now but its not fixed?

"put the large ball in the box" still gives small box as an option

**Comment by jeffpolk230** [comment]
fixed

**Comment by HalfLeif** [comment]
Great

**Comment by HalfLeif** [comment]
Merging it into development

**Comment by jeffpolk230** [comment]
Done :D
