### ISSUE TITLE
Planner fails to find solution to very simple case

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#16]
See image. The command "put the small ball on the table" fails with a planning timeout. However, from what I understand, we just have to move the two boxes from the table and move the ball there instead, something which should be very simple. Why does it fail to find this simple solution???

![capture](https://cloud.githubusercontent.com/assets/1454000/7789137/87fbb500-0256-11e5-8cf9-4300ff305ab1.PNG)

**Comment by Plankton555** [comment]
Even this fails... Something must be wrong somewhere...

![capture2](https://cloud.githubusercontent.com/assets/1454000/7789151/0a618c0e-0257-11e5-897e-af4e589e39d4.PNG)

**Comment by Plankton555** [comment]
Might it be that a ball cannot be directly on top of a table, but must be inside a box or something to not "roll off"? If so, the interpreter should throw an error instead of letting the planner time out.

**Comment by HalfLeif** [comment]
Yes exactly. This is another thing that used to work :P, will debug this issue now

**Comment by HalfLeif** [comment]
It is the empty interpretation...

**Comment by HalfLeif** [comment]
Fixed in development. This fix shouldn't interfer with Jeffs ambiguity stuff
