### ISSUE TITLE
Planning timeout if location is a non-existing object

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#19]
See picture. If the target object is non-existing, an error "Interpretation error: Can't find such an object to grasp." is thrown. However, if the LOCATION is non-existing, no such error is thrown. Instead, the planner times out since it cannot find any solution.

![capture](https://cloud.githubusercontent.com/assets/1454000/7796320/910791c2-02de-11e5-80df-47dda1442c88.PNG)

**Comment by HalfLeif** [comment]
I'll look into this.

**Comment by HalfLeif** [comment]
I cannot recreate this bug? In development, small world:

grasp a box
put it above a pyramid

The interpreter correctly gives an error...

**Comment by HalfLeif** [comment]
Also for the same input you have above, Interpreter correctly gives error...

Can you recreate it Björn?

**Comment by Plankton555** [comment]
Will pull the latest from development and try.

**Comment by Plankton555** [comment]
I can't seem to recreate this either. Don't know what happened :P 

Closing this.
