### ISSUE TITLE
Support for different words

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#2]
http://ai-course-tin172-dit410.github.io/project.html

**Comment by HalfLeif** [comment]
Inside and ontop can fall through in the switch statement, they are quite equivalent.

case "inside":
case "ontop":
    ....

I'm merging this specific implementation to development now (for the word "inside")

**Comment by HalfLeif** [comment]
Btw Björn, the case "above" already has a structure for it but part of the heuristic function is missing, so I will fix that one as well

**Comment by Plankton555** [comment]
Note: The cases "beside", "left of" and "right of" are unimplemented in the Planner.

**Comment by Plankton555** [comment]
The words "beside", "left of" and "right of" now works. However, they have no implemented heuristic yet (it's set to 0 right now).

Also, do we want the objects to be on the same height level, or do we just care about whether they are in stacks to the left of, right of or exactly beside each other? If we want same height level, some more work is needed (not much).

**Comment by HalfLeif** [comment]
Just being in an adjacent stack should be sufficient, placing something at the exact same height might even be impossible in some worlds

**Comment by Plankton555** [comment]
When testing/implementing heuristics for "beside", "right of" and "left of", I noticed that the program throws interpretation errors sometimes even though it shouldn't (there are valid interpretations). New issue created #6.

**Comment by Plankton555** [comment]
Simple heuristics added for all three expressions. All of these heuristics only counts stacks/columns, nothing regarding costs for picking/dropping or if there are stacks.

Beside: counts the difference in columns from target to each side of the 'beside' object, taking the minimum of these two as heuristic.
Left of: counts the difference in columns until the target is left of the 'leftof' object. If target is already left of the 'leftof' object, heuristic is 0.
Right of: same as 'left of', but sides switched.

**Comment by HalfLeif** [comment]
The command "put it" is not yet implemented.

Example: in shrdlite.html:
grasp the white ball
drop it on the floor

Note, they need to be run after one another, otherwise the arm is empty...

**Comment by Plankton555** [comment]
Yes, I didn't think about using backwards reference ('it') when I went through the words.

**Comment by Plankton555** [comment]
Support for 'it' now added, merged into development branch.
