### ISSUE TITLE
Program fails to understand ambiguity clarification

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#20]
Related to issue #17. Program fails to understand clarification. Not sure exactly what might be wrong since I haven't worked on this code. See picture below. Could it be something regarding "object"? (I was trying that out when I found the problem...)

Tagging @jeffpolk230 

![capture](https://cloud.githubusercontent.com/assets/1454000/7796445/a6bbd7b6-02df-11e5-9ab9-b01172010d2f.PNG)

**Comment by HalfLeif** [comment]
Jeff?

**Comment by jeffpolk230** [comment]
In lecture
Will take a later tonight

On Monday, May 25, 2015, Leif Schelin notifications@github.com wrote:

> Jeff?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Qthulu/shrdlite-course-project/issues/20#issuecomment-105241840
> .

## 

Jeff

**Comment by jeffpolk230** [comment]
Solved in development 
![screen shot 2015-05-25 at 6 53 54 pm](https://cloud.githubusercontent.com/assets/1535566/7800045/9883abf8-030f-11e5-8c42-927c170e1850.png)

now very lovely refinement can be done :D
[WARNING] 
refinement only can be done in "net"
please try not to report more bugs related to refinement on "loc"
i will try to catch that crash!

**Comment by jeffpolk230** [comment]
Also please ignore the not correct "Do you mean ..." at the moment, that has to do with issue 15 
which i will fix together

**Comment by jeffpolk230** [comment]
Working nicely at least :)

**Comment by jeffpolk230** [comment]
the latest version on development is really slick :)
it ignores miss-typed refinements such as "box" -> "bx"
![screen shot 2015-05-25 at 7 31 02 pm](https://cloud.githubusercontent.com/assets/1535566/7800366/9a55b19c-0314-11e5-901a-2f0b552c2d80.png)
