### ISSUE TITLE
Planning timeout for a solution that shouldn't be that hard

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#21]
See picture. The planner times out despite the "current cost" being only 17. Is there something weird going on with the heuristic or is the branching factor just too high?

![capture](https://cloud.githubusercontent.com/assets/1454000/7796545/92ba57be-02e0-11e5-9a35-7a762877dafb.PNG)

**Comment by Plankton555** [comment]
I tried increasing the max nr of iterations to 50k and it found a solution after 28953 iterations. Maybe we should increase the limit from 25k?

**Comment by HalfLeif** [comment]
If something this easy takes more than a few hundred iterations, something is off with the heuristic...

**Comment by HalfLeif** [comment]
The leftof/rightof/beside heuristics are not as developed as those for ontop and above

**Comment by HalfLeif** [comment]
I will look into this. For some reason, it works really well in the complex world. Perhaps I know why...

**Comment by HalfLeif** [comment]
Fixed.
