### ISSUE TITLE
Unimplemented command

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#23]
Right now, the command "put all boxes on the floor" is being interpreted as "any". Maybe something we don't have time to fix, but I guess this could be regarded as a bug or "non-implemented feature".

![capture](https://cloud.githubusercontent.com/assets/1454000/7796709/663e193a-02e2-11e5-9f39-b503cb177ca9.PNG)

**Comment by HalfLeif** [comment]
As I understand it, support for "all" is an extension by itself.

**Comment by Plankton555** [comment]
Yes, that might be true. Closing this then.
