### ISSUE TITLE
Prepare DEMO

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#24]
After finding and squishing bugs, we should:
1. Decide a series of commands that demonstrates the capabilities of the program.
2. Make a new branch "demo" which we make sure (extra sure) that it handles all demo commands.
3. Check the timing so it will take about 5 min.

**Comment by Plankton555** [comment]
(Sorry, tried to assign all three of us, didn't work. Tagging instead. @Plankton555 @HalfLeif @jeffpolk230 )

**Comment by HalfLeif** [comment]
I propose we at least use the Complex world, perhaps with some minor modification in color to better show the ambiguity.

What we want to show (at least):
- fast heuristics for some difficult commands
- ambiguity on multiple parsings

**Comment by HalfLeif** [comment]
This was quite fun to watch:

put the green plank left of the large brick

> This plan has 34 actions.
> Completed in 2211 iterations.
> What can I do for you today?

put the red plank above the yellow box

> This plan has 38 actions.
> Completed in 3350 iterations.
