### ISSUE TITLE
Ambiguity error has returned

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#26]
Small world:

put the ball in a box

> Do you mean large red box ? large yellow box ? small blue box ?

So the wrong clarification question is printed. However, the program seems to know it really is the ball because if you answer "large", it takes the large ball. But if you answer "yellow" it gives error. Furthermore, the following is printed in the terminal:

```
{ status: 'SoftAmbiguity',
  targets: [ 'e', 'f' ],
  common: { dictionary: { table: {}, nElements: 0, toStr: [Function: defaultToString] } },
  ambiguousObjs:
   [ { form: 'ball', size: 'large', color: 'black' },
     { form: 'ball', size: 'small', color: 'black' } ] }
```

Jeff?

**Comment by jeffpolk230** [comment]
Fixed in development :)
(this was actually done last night, but i failed to remember this morning)
however, this fix result in reopen on 15 ! 
(they're conjugating at the moment, will have to take very careful remedy on 15)

**Comment by jeffpolk230** [comment]
issue 15 is just some result not elegant, but this issue is far more problematic !
therefore, in case insufficient time before wednesday, we will stick with current implementation so this issue will not come back

**Comment by HalfLeif** [comment]
Yes, we should probably stop fixing soon so we do not accidentally create new issues (since we don't have a test suite). I propose that we tomorrow morning create the DEMO branch and make sure to only use commands that the DEMO branch supports. Of course, it should be tested so that we are aware of any issues anyway...

**Comment by jeffpolk230** [comment]
Agree with stop fixing 
I've pushed my latest work on development
Only last thing i MIGHT fix would be "catching crash on refinement of loc"
