### ISSUE TITLE
Interpreter.canSupport() is unable to handle cases where 'above' or 'below' are NULL

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#4]
I'm not sure if the function canSupport() should do something about it, or if something has gone seriously wrong calling the function with NULL values.

**Comment by Plankton555** [comment]
This also causes the program to be unable to handle commands like "put the red box on the floor". Anything that involves the floor causes 'below' to be NULL.

**Comment by HalfLeif** [comment]
The canSupport() should never be called with null...

**Comment by HalfLeif** [comment]
I dont know why "floor" turns up as null. The problem could be in findTargetEntities but it shouldnt...

I dont have time to fix it tonight though

**Comment by Plankton555** [comment]
No problem, as long as we remember to fix this problem before the final handin :)

**Comment by HalfLeif** [comment]
Found the floor issue bug, working on a fix

**Comment by HalfLeif** [comment]
Fixed in branch development.

Also noted that "put _ under the floor" gives no interpretation (as it should).
