### ISSUE TITLE
Ambiguity error despite not ambiguous

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#5]
In a world with only one table (using "make run"), the following command works
"put the blue table below the blue box"
but not
"put the table below the blue box"

When the colour is not specified, this error is thrown

> Interpretation error There are several objects that fit the description

**Comment by HalfLeif** [comment]
Can you reproduce this in a separate branch? If you were using the medium world, there is also a red table that could have caused the ambiguity.

**Comment by Plankton555** [comment]
I'm on it

**Comment by Plankton555** [comment]
This can be reproduced by checking out the branch bugfix_#5 and just running "make run" in a terminal.

The program will then run the two commands, one after the other. The first command will finish in 39 iterations while the second will give "Interpretation error There are several objects that fit the description".

**Comment by HalfLeif** [comment]
If one changes from "the" to "a", one sees that the conflicting object:
above(m,g) | above(m,h)

However, the object h is not part of this world. Working on a fix.

**Comment by HalfLeif** [comment]
Fixed, pushed to development.
