### ISSUE TITLE
How should one interpret beside the floor? Simply disallow or return true? It is currently not handled at all...

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#8]
For example:
node shrdlite-offline.js medium "put the red plank beside the floor"

If it is "leftOf" the floor, one could of course check that the target object is not at the very far right end...

**Comment by Plankton555** [comment]
For me it feels like "left of / right of / beside the floor" makes no sense. So maybe disallow it?

A classmate said that she would interpret "put X beside the floor" as put X beside an open floor space. I don't know if we maybe want that or not?

**Comment by HalfLeif** [comment]
I would say either disallow or simply state that it is already beside the floor :)

**Comment by Plankton555** [comment]
So, should I implement a disallowance (is that even a word?) of "beside/left of/right of the floor" then?

**Comment by HalfLeif** [comment]
Sure, go ahead

**Comment by Plankton555** [comment]
On it. Just a note: the command "put the floor on a table" also crashes the program. Think I'll add checks to see if we do stupid things with the floor (allowing to put things ON the floor, of course).

**Comment by Plankton555** [comment]
How about "put the box above the floor"? Right now, that gives "Interpretation error: Found no legal interpretation". However, "put the box on the floor" works as it should.

**Comment by Plankton555** [comment]
Fixed in commit 2a5bb1cb4748.

Trying to move the floor now gives an error "You cannot move the floor". Trying to do something other than moving an object ontop/inside of the floor gives an error "You can only put objects ON the floor".

I have tried all test commands I could think of, all works. I might have missed something though :P (I want a test suite xD)
