### ISSUE TITLE
Interpretation error with "that is"

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#9]
This is not ambiguous but is interpreted wrong...
node shrdlite-offline.js medium "put a ball that is on the floor beside the green plank"

**Comment by HalfLeif** [comment]
Currently works, will do some refactoring before push.

**Comment by Plankton555** [comment]
Put a (ball that is on the floor) beside the green plank
vs
Put a ball that is on (the floor beside the green plank)

This is ambiguous, right, but ambigous in a way that at least I think is non-sensical (since the floor wouldn't be beside a plank)?

**Comment by HalfLeif** [comment]
Perhaps it is, but not in this grammar :) Anyway, it turned out to require some effort but it works now (for any given depth of Objects in Objects using recursion). I did a major refactoring to avoid duplicating code. It is currently in development. So if you are working in a separate branch, it is best to merge in development to it.
